<?php

namespace AppBundle\Repository;

/**
 * PersonnePhysiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnePhysiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
