<?php

namespace AppBundle\Repository;

/**
 * PersonneMoraleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneMoraleRepository extends \Doctrine\ORM\EntityRepository
{
}
