<?php

namespace AppBundle\Repository;

/**
 * ProtocoleInstructionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocoleInstructionRepository extends \Doctrine\ORM\EntityRepository
{
}
